export const cargoByMonth: Record<number, string> = {
  1: 'Desenvolvedor',
  2: 'Engenheiro',
  3: 'Analista',
  4: 'Arquiteto',
  5: 'Tester',
  6: 'Scrum Master',
  7: 'Tech Lead',
  8: 'Product Owner',
  9: 'UX Designer',
  10: 'DevOps',
  11: 'Pesquisador de IA',
  12: 'Data Scientist',
};

export const areaByDay: Record<number, string> = {
  1: 'Web3',
  2: 'Backend',
  3: 'Games',
  4: 'Sustentação',
  5: 'Mobile',
  6: 'Cloud',
  7: 'Automação',
  8: 'Frontend',
  9: 'Fintech',
  10: 'Banco de Dados',
  11: 'Observabilidade',
  12: 'Segurança',
  13: 'Fullstack',
  14: 'Startups',
  15: 'IA Generativa',
  16: 'VR/AR',
  17: 'API',
  18: 'Blockchain',
  19: 'Produto',
  20: 'Chatbot',
  21: 'Machine Learning',
  22: 'Sistemas',
  23: 'Open Source',
  24: 'SaaS',
  25: 'Growth Tech',
  26: 'IoT',
  27: 'E-commerce',
  28: 'DevRel',
  29: 'QA',
  30: 'API First',
  31: 'Observabilidade',
};

export const techByLastDigit: Record<number, string> = {
  0: 'Java',
  1: 'PHP',
  2: 'Python',
  3: 'Kotlin',
  4: 'Swift',
  5: 'Ruby',
  6: 'Go',
  7: 'C#',
  8: 'TypeScript',
  9: 'JavaScript',
};